### ISSUE TITLE
module don't build with nginx 1.8.0

### ISSUE THREAD

**Issue by Nmishin** [stogh/ngx_http_auth_pam_module#6]
-o objs/addon/ngx_http_auth_pam_module/ngx_http_auth_pam_module.o \
		../ngx_http_auth_pam_module/ngx_http_auth_pam_module.c
../ngx_http_auth_pam_module/ngx_http_auth_pam_module.c:13:31: error: security/pam_appl.h: No such file or directory
cc1: warnings being treated as errors
../ngx_http_auth_pam_module/ngx_http_auth_pam_module.c:59: error: 'struct pam_response' declared inside parameter list
../ngx_http_auth_pam_module/ngx_http_auth_pam_module.c:59: error: its scope is only this definition or declaration, which is probably not what you want
../ngx_http_auth_pam_module/ngx_http_auth_pam_module.c:59: error: 'struct pam_message' declared inside parameter list
../ngx_http_auth_pam_module/ngx_http_auth_pam_module.c:126: error: 'struct pam_response' declared inside parameter list
../ngx_http_auth_pam_module/ngx_http_auth_pam_module.c: In function 'free_resp':
../ngx_http_auth_pam_module/ngx_http_auth_pam_module.c:132: error: invalid use of undefined type 'struct pam_response'
../ngx_http_auth_pam_module/ngx_http_auth_pam_module.c:132: error: dereferencing pointer to incomplete type
../ngx_http_auth_pam_module/ngx_http_auth_pam_module.c:134: error: invalid use of undefined type 'struct pam_response'
../ngx_http_auth_pam_module/ngx_http_auth_pam_module.c:134: error: dereferencing pointer to incomplete type
../ngx_http_auth_pam_module/ngx_http_auth_pam_module.c:134: error: invalid use of undefined type 'struct pam_response'
../ngx_http_auth_pam_module/ngx_http_auth_pam_module.c:134: error: dereferencing pointer to incomplete type
../ngx_http_auth_pam_module/ngx_http_auth_pam_module.c:135: error: invalid use of undefined type 'struct pam_response'
../ngx_http_auth_pam_module/ngx_http_auth_pam_module.c:135: error: dereferencing pointer to incomplete type
../ngx_http_auth_pam_module/ngx_http_auth_pam_module.c:136: error: invalid use of undefined type 'struct pam_response'
../ngx_http_auth_pam_module/ngx_http_auth_pam_module.c:136: error: dereferencing pointer to incomplete type
../ngx_http_auth_pam_module/ngx_http_auth_pam_module.c: At top level:
../ngx_http_auth_pam_module/ngx_http_auth_pam_module.c:151: error: 'struct pam_response' declared inside parameter list
../ngx_http_auth_pam_module/ngx_http_auth_pam_module.c:151: error: 'struct pam_message' declared inside parameter list
../ngx_http_auth_pam_module/ngx_http_auth_pam_module.c:150: error: conflicting types for 'ngx_auth_pam_talker'
../ngx_http_auth_pam_module/ngx_http_auth_pam_module.c:58: note: previous declaration of 'ngx_auth_pam_talker' was here
../ngx_http_auth_pam_module/ngx_http_auth_pam_module.c: In function 'ngx_auth_pam_talker':
../ngx_http_auth_pam_module/ngx_http_auth_pam_module.c:162: error: 'PAM_CONV_ERR' undeclared (first use in this function)
../ngx_http_auth_pam_module/ngx_http_auth_pam_module.c:162: error: (Each undeclared identifier is reported only once
../ngx_http_auth_pam_module/ngx_http_auth_pam_module.c:162: error: for each function it appears in.)
../ngx_http_auth_pam_module/ngx_http_auth_pam_module.c:165: error: invalid application of 'sizeof' to incomplete type 'struct pam_response' 
../ngx_http_auth_pam_module/ngx_http_auth_pam_module.c:172: error: invalid use of undefined type 'struct pam_response'
../ngx_http_auth_pam_module/ngx_http_auth_pam_module.c:172: error: dereferencing pointer to incomplete type
../ngx_http_auth_pam_module/ngx_http_auth_pam_module.c:173: error: invalid use of undefined type 'struct pam_response'
../ngx_http_auth_pam_module/ngx_http_auth_pam_module.c:173: error: dereferencing pointer to incomplete type
../ngx_http_auth_pam_module/ngx_http_auth_pam_module.c:176: error: dereferencing pointer to incomplete type
../ngx_http_auth_pam_module/ngx_http_auth_pam_module.c:177: error: 'PAM_PROMPT_ECHO_ON' undeclared (first use in this function)
../ngx_http_auth_pam_module/ngx_http_auth_pam_module.c:179: error: invalid use of undefined type 'struct pam_response'
../ngx_http_auth_pam_module/ngx_http_auth_pam_module.c:179: error: dereferencing pointer to incomplete type
../ngx_http_auth_pam_module/ngx_http_auth_pam_module.c:181: error: 'PAM_PROMPT_ECHO_OFF' undeclared (first use in this function)
../ngx_http_auth_pam_module/ngx_http_auth_pam_module.c:182: error: invalid use of undefined type 'struct pam_response'
../ngx_http_auth_pam_module/ngx_http_auth_pam_module.c:182: error: dereferencing pointer to incomplete type
../ngx_http_auth_pam_module/ngx_http_auth_pam_module.c:185: error: passing argument 2 of 'free_resp' from incompatible pointer type
../ngx_http_auth_pam_module/ngx_http_auth_pam_module.c:126: note: expected 'struct pam_response *' but argument is of type 'struct pam_response *'
../ngx_http_auth_pam_module/ngx_http_auth_pam_module.c:191: error: 'PAM_SUCCESS' undeclared (first use in this function)
../ngx_http_auth_pam_module/ngx_http_auth_pam_module.c: At top level:
../ngx_http_auth_pam_module/ngx_http_auth_pam_module.c:231: error: expected ')' before '*' token
../ngx_http_auth_pam_module/ngx_http_auth_pam_module.c:262: error: expected ')' before '*' token
../ngx_http_auth_pam_module/ngx_http_auth_pam_module.c: In function 'ngx_http_auth_pam_authenticate':
../ngx_http_auth_pam_module/ngx_http_auth_pam_module.c:281: error: storage size of 'conv_info' isn't known
../ngx_http_auth_pam_module/ngx_http_auth_pam_module.c:282: error: 'pam_handle_t' undeclared (first use in this function)
../ngx_http_auth_pam_module/ngx_http_auth_pam_module.c:282: error: 'pamh' undeclared (first use in this function)
../ngx_http_auth_pam_module/ngx_http_auth_pam_module.c:323: error: implicit declaration of function 'pam_start'
../ngx_http_auth_pam_module/ngx_http_auth_pam_module.c:326: error: 'PAM_SUCCESS' undeclared (first use in this function)
../ngx_http_auth_pam_module/ngx_http_auth_pam_module.c:334: error: implicit declaration of function 'add_request_info_to_pam_env'
../ngx_http_auth_pam_module/ngx_http_auth_pam_module.c:338: error: implicit declaration of function 'pam_authenticate'
../ngx_http_auth_pam_module/ngx_http_auth_pam_module.c:339: error: 'PAM_DISALLOW_NULL_AUTHTOK' undeclared (first use in this function)
../ngx_http_auth_pam_module/ngx_http_auth_pam_module.c:343: error: implicit declaration of function 'pam_end'
../ngx_http_auth_pam_module/ngx_http_auth_pam_module.c:348: error: implicit declaration of function 'pam_acct_mgmt'
../ngx_http_auth_pam_module/ngx_http_auth_pam_module.c:281: error: unused variable 'conv_info'
make[1]: *** [objs/addon/ngx_http_auth_pam_module/ngx_http_auth_pam_module.o] Error 1
make[1]: Leaving directory `/usr/build/nginx-1.8.0'
make: *** [build] Error 2

nginx configuring with options:
nginx-1.8.0]# ./configure --add-module=../mod_zip-1.1.6 --add-module=../nginx-auth-ldap --add-module=../nginx_upload_module-2.2.0 --add-module=../nginx-upload-progress-module-master --add-module=../nginx-upstream-fair --add-module=../ngx_http_auth_pam_module --user=nginx --group=nginx --prefix=/usr/share/nginx --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --http-client-body-temp-path=/var/lib/nginx/tmp/client_body --http-proxy-temp-path=/var/lib/nginx/tmp/proxy --http-fastcgi-temp-path=/var/lib/nginx/tmp/fastcgi --http-uwsgi-temp-path=/var/lib/nginx/tmp/uwsgi --http-scgi-temp-path=/var/lib/nginx/tmp/scgi --pid-path=/var/run/nginx.pid --lock-path=/var/lock/subsys/nginx --with-http_secure_link_module --with-http_random_index_module --with-http_ssl_module --with-http_realip_module --with-http_addition_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gzip_static_module --with-http_degradation_module --with-http_stub_status_module --with-http_perl_module --with-http_geoip_module --with-mail --with-mail_ssl_module --with-cc-opt='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic' --with-ipv6 --with-file-aio

**Comment by huadong** [comment]
pam-devel should be installed before compiling
